<?php

namespace Tests\Feature\Repositories;

use App\Data\Media\CreateMediaData;
use App\Models\Media\Media;
use Tests\TestCase;
use App\Repositories\Media\MediaRepository as Repository;

class MediaRepositoryTest extends TestCase
{
    protected Repository $repo;

    protected function setUp(): void
    {
        $this->repo = app()->make(Repository::class);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @group MediaRepository
     */
    public function method_create()
    {
        $userId = 1;
        $filename = 'method_create.jpg';
        $mimeType = 'image/jpeg';
        $fileSize = 1424;

        $data = new CreateMediaData($userId, $filename, $mimeType, $fileSize);
        $this->repo->create($data);

        $this->assertDatabaseHas(Media::class, $data->toArray());
    }
}
