@startuml
!include ../tables/content/comments.puml
!include ../tables/content/post_tag.puml
!include ../tables/content/posts.puml
!include ../tables/content/tags.puml
!include ../tables/users.puml

posts -{ comments
post_tag -- tags
post_tag -- posts
posts -- users
comments -- users
tags -- users
comments -{ comments
@enduml
