@startuml
object comments {
    App\Models\Content\Comment
    __
    + id

    - user_id (UBI)
    - commentable_id (UBI)
    - commentable_type (string)

    body (text)
    created_at
    updated_at
}
@enduml
