@startuml
object posts {
    App\Models\Content\Post
    __
    + id
    - user_id (UBI)

    title (string)
    rating (integer)
    slug (string)
    total_views (UI)
    total_comments (UI)

    created_at
    updated_at
}
@enduml
