@startuml
object post_stats {
    App\Models\Content\PostStat
    __
    + id
    - post_id (UID)

    positive_votes (UID)
    negative_votes (UID)

    views (UID)
    comments (UID)

    created_at
    updated_at
}
@enduml
