@startuml
object tags {
    App\Models\Content\Tag
    __
    + id
    - user_id (UBI)

    title (string)
    body (text)
    slug (string)
    rating (integer)
    total_posts (integer)

    created_at
    updated_at
}
@enduml
