<?php

namespace Tests\Unit\Redis;

use App\Plugins\Redis\Model;
use PHPUnit\Framework\TestCase;

class RedisTestModel extends Model {}

class ModelTest extends TestCase
{
    protected RedisTestModel $model;

    protected function setUp(): void
    {
        $this->prepareTest();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @group RedisModel
     */
    public function prepare_test_cleans_redis_properly()
    {
        RedisTestModel::create(['id' => 1]);
        RedisTestModel::create(['id' => 2]);
        RedisTestModel::create(['id' => 3]);
        RedisTestModel::create(['id' => 4]);

        $this->assertTrue(count(RedisTestModel::all()) === 4);

        $this->prepareTest();
        $this->assertTrue(count(RedisTestModel::all()) === 0);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function model_takes_redis_key_from_static_class()
    {
        $this->assertTrue($this->model->redis->getRedisKey() === 'redis_test_model', 'Redis key mismatch');
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_create_works_the_same_from_static_and_this()
    {
        $data = $this->getModelData();
        $model = $this->model->create($data);
        $this->assertDataArrayEqualsModelAttributes($data, $model);

        $this->prepareTest();

        $model = RedisTestModel::create($data);
        $this->assertDataArrayEqualsModelAttributes($data, $model);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_update_works_the_same_from_static_and_this()
    {
        $id = 25;
        $data = $this->getModelData($id);

        RedisTestModel::create($data);
        $data['updated_value'] = 'some value';
        RedisTestModel::update($id, $data);

        $model = RedisTestModel::find($id);
        $this->assertDataArrayEqualsModelAttributes($data, $model);

        $data['updated_value'] = 'new some value';
        RedisTestModel::update($id, $data);

        $model = RedisTestModel::find($id);
        $this->assertDataArrayEqualsModelAttributes($data, $model);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_delete_works_from_this_and_static()
    {
        $data = $this->getModelData(26);
        $model1 = RedisTestModel::create($data);
        $data = $this->getModelData(15);
        $model2 = RedisTestModel::create($data);

        $this->assertTotalRecordsEqual(2);

        RedisTestModel::delete($model1->id);
        $this->assertTotalRecordsEqual(1);

        $model2->delete();
        $this->assertTotalRecordsEqual(0);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_delete_all_works_from_this_and_static()
    {
        $this->createMultipleModels(4);

        $this->assertTotalRecordsEqual(4);
        RedisTestModel::deleteAll();
        $this->assertTotalRecordsEqual(0);

        $this->createMultipleModels(4);

        $this->assertTotalRecordsEqual(4);
        $this->model->deleteAll();
        $this->assertTotalRecordsEqual(0);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_all_works_from_this_and_static()
    {
        $this->createMultipleModels(4);
        $all = RedisTestModel::all();

        $this->assertTrue(count($all) === 4);
        foreach ($all as $model) {
            $this->assertTrue($model instanceof Model);
        }

        $this->createMultipleModels(4);
        $all = $this->model->all();

        $this->assertTrue(count($all) === 4);
        foreach ($all as $model) {
            $this->assertTrue($model instanceof Model);
        }
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_delete_multiple_works_from_this_and_static()
    {
        $this->createMultipleModels(4);

        RedisTestModel::deleteMultiple([1, 2]);
        $this->assertTotalRecordsEqual(2);

        $this->model->deleteMultiple([3, 4]);
        $this->assertTotalRecordsEqual(0);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_get_where_works_from_this_and_static()
    {
        foreach (range(1, 6) as $id) {
            $data = ['id' => $id, 'prop' => "value $id", 'const' => 'const value'];
            RedisTestModel::create($data);
        }

        $models = RedisTestModel::getWhere('id', 6);
        $this->assertCount(1, $models);
        $models = RedisTestModel::getWhere('const', 'const value');
        $this->assertCount(6, $models);

        $models = $this->model->getWhere('id', 6);
        $this->assertCount(1, $models);
        $models = $this->model->getWhere('const', 'const value');
        $this->assertCount(6, $models);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_get_where_returns_null_if_not_found_records()
    {
        $res = RedisTestModel::getWhere('id', 1);

        $this->assertTrue($res === null);
    }

    // * @method find(int $id)
    /**
     * @test
     * @group RedisModel
     */
    public function method_find_works_from_this_and_static()
    {
        $this->createMultipleModels(2);

        $model = RedisTestModel::find(1);
        $this->assertTrue(1 === $model->id);

        $model = $this->model->find(2);
        $this->assertTrue(2 === $model->id);
    }

    /**
     * @test
     * @group RedisModel
     */
    public function method_find_returns_null_if_record_wasnt_found()
    {
        $res = RedisTestModel::find(1);
        $this->assertTrue($res === null);
    }

    private function createMultipleModels(int $amount) {
        foreach(range(1, $amount) as $id) {
            RedisTestModel::create($this->getModelData($id));
        }
    }

    private function assertTotalRecordsEqual(int $number)
    {
        $this->assertTrue(count(RedisTestModel::all()) === $number);
    }

    private function assertDataArrayEqualsModelAttributes(array $data, Model $model)
    {
        foreach ($data as $key => $value) {
            $this->assertTrue($value === $model->{$key});
        }
    }

    private function getModelData(int $id = 1): array
    {
        return [
            'id' => $id,
            'first' => 'Test Value',
            'second' => 15
        ];
    }

    private function getRedisTestModel(): RedisTestModel
    {
        return app()->make(RedisTestModel::class);
    }

    private function prepareTest()
    {
        $this->model = $this->getRedisTestModel();
        $this->model->deleteAll();
    }
}
